version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - gocyclo
    - goconst
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    gocyclo:
      min-complexity: 30
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
