[project]
name = "layrz-forms"
version = "3.0.0"
description = "Layrz forms and tools for Python"
authors = [{ name = "Golden M, Inc.", email = "software@goldenm.com" }]
requires-python = ">=3.14"

maintainers = [
  { name = "Kenny Mochizuki", email = "kenny@goldenm.com" },
  { name = "Miguel Zauzich", email = "miguel@goldenm.com" },
  { name = "Ángel Prieto", email = "aprieto@goldenm.com" },
]

readme = "README.md"

license = "MIT"

keywords = ["sdk", "goldenm", "layrz", "forms"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "pydantic>=2.13.4",
  "strawberry-graphql>=0.287.0",
]

[project.urls]
Repository = "https://github.com/goldenm-software/layrz-forms"
Changelog = "https://github.com/goldenm-software/layrz-forms/blob/main/CHANGELOG.md"

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"


[dependency-groups]
dev = [
  "build>=1.2.2.post1",
  "pytest>=7.0.0",
  "pytest-asyncio>=0.23.0",
  "pytest-cov>=5.0.0",
  "ruff>=0.9.8",
  "twine>=6.1.0",
  "ty>=0.0.65",
]

[tool.ruff]
indent-width = 2
line-length = 120

exclude = [".venv"]

[tool.ruff.lint]
ignore = [
  "F401",   # Unused import
  "E701",   # Multiple statements on one line
  "TD003",  # Missing issue link
  "ANN401", # Any type annotation
]

select = [
  "I",   # isort
  "E",
  "W",   # pycodestyle
  "F",   # pyflakes
  "B",   # flakes8-bugbear
  "TD",  # flake8-todo
  "DJ",  # flake8-django
  "DTZ", # flake8-datetimez
  "T20", # flake8-print # En un futuro
  "PYI", # flake8-pyi
  "ANN", # flake8-annotations
]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

[tool.ty.environment]
python-version = "3.14"

[tool.ty.src]
exclude = [
  ".venv/",
  ".ruff_cache/",
  ".mypy_cache/",
  "**/migrations/**",
  "**/templates/**",
]


[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
